apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    resources: {}
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
