apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: deployment-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: {}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 81
      targetPort: 80
