apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-blue
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      namespace: apps
      labels:
        app: nginx-color
    spec:
      containers:
        - name: nginx-blue
          image: jaksonsneider/nginx:blue
          ports:
            - containerPort: 80
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: apps
spec:
  selector:
    app: nginx-color
  ports:
    - name: "app-service-nginx"
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
